// blog_new/foreground_react/src/pages/MessageManagement/EditorialForm.js
import React from 'react';
import { Form } from 'antd';
import { UrlEnum } from '@/assets/Enum';
import EditorialFormConfig from '@/pages/EditorialFormConfig';

const { getModalForm } = EditorialFormConfig;
const { AdminMessageAPI: { INSERT } } = UrlEnum;

@Form.create()
class EditorialForm extends React.PureComponent {
  state = {
    initialFormData: {},
  };

  componentDidMount = () => {
    const { formItem = {} } = this.props;
    if (formItem.id) this.formatInitialFormData(formItem);
  };

  formatInitialFormData = (formItem, extraObj) => {
    const { id, from, fromMail,message: preMessage } = formItem;
    const to = { key: from?from.id:fromMail, label: from?from.nickName:fromMail };
    const initialFormData = { id, to, preMessage };
    this.setState({ initialFormData, ...extraObj });
  };

  toggleEdit = obj => {
    const {
      form,
      request,
      cleanFormItem,
      toggleEditorialPanel,
      formItem: { id, parentId: pid },
    } = this.props;
    if (obj === 'cancel') {
      form.resetFields();
      toggleEditorialPanel();
      cleanFormItem();
      request();
      return;
    }
    form.validateFields((err, values) => {
      if (err) return;
      const { to={} } = values;
      const netUrl = INSERT.url;
      const parentId = pid === 0 ? id : pid;
      const toId = typeof to.key === "number" ? to.key : undefined;
      const toMail = to.key!==undefined&&typeof to.key !== "number" && to.key !== "博主" ? to.key : "无";
      request({ ...values, netUrl, parentId, toId,toMail,fromMail:"无" });
      toggleEditorialPanel();
      cleanFormItem();
      form.resetFields();
    });
  };

  render() {
    const { form, editorialPanelVisible } = this.props;
    const { initialFormData } = this.state;
    const formConfig = [
      initialFormData.id !== undefined && {
        fieldId: 'to',
        label: '被回复人',
        rules: [{ required: true, message: '评论人是必须的' }],
        fieldType: 'select',
        fieldProps: {
          options: [],
          labelInValue: true,
          disabled: true,
          style: { width: '94%' },
        },
        formItemLayout: { labelCol: { span: 4 } },
      },
      initialFormData.id !== undefined && {
        fieldId: 'preMessage',
        label: '内容',
        fieldType: "node",
        fieldNode: <span>{initialFormData.preMessage}</span>,
        fieldProps: {
          style: { width: '94%' },
        },
        formItemLayout: { labelCol: { span: 4 } },
      },
      {
        fieldId: 'isTop',
        label: '是否置顶',
        rules: [{ required: true, message: '该项是必须的' }],
        fieldType: 'select',
        fieldProps: {
          options: [{ value: 1, label: '是' }, { value: 0, label: '否' }],
          style: { width: '94%' },
        },
        initialValue: 1,
        formItemLayout: { labelCol: { span: 4 } },
      },
      {
        fieldId: 'message',
        label: '留言',
        rules: [{ required: true, message: '留言内容是必须的' }],
        fieldProps: { style: { width: '94%' }, autosize: true, rows: 2 },
        fieldType: 'textArea',
        formItemLayout: { labelCol: { span: 4 } },
      },
    ];
    return getModalForm({
      initialFormData,
      editorialPanelVisible,
      toggleEdit: this.toggleEdit,
      form,
      formConfig,
      INSERT,
      UPDATE: INSERT,
      width: 600,
    });
  }
}

export default EditorialForm;

// blog_new/foreground_vue/src/pages/MsgManagement/EditorialForm.vue
<template>
  <div id="message-edit">
    <a-modal
      :title="AdminMessageAPI.INSERT.desc['zh_CN']"
      :visible="editorialPanelVisible"
      width="100%"
      okText="确定"
      cancelText="取消"
      @ok="toggleEdit"
      @cancel="toggleEdit('cancel')"
    >
      <a-form :form="form" layout="horizontal">
        <a-form-item label="留言人" :label-col="{span:5}" :wrapper-col="{span:15}" v-if="initialFormData.id !== undefined">
          <a-select 
            v-decorator="['to',{rules:[{required:true,message:'评论人是必须的！'}],initialValue:initialFormData.to}]" 
            :disabled="true" 
            :labelInValue="true" 
          />
        </a-form-item>
        <a-form-item label="内容" :label-col="{span:5}" :wrapper-col="{span:15}" v-if="initialFormData.id !== undefined">
          <span>{{initialFormData.preMessage}}</span>
        </a-form-item>
        <a-form-item label="置顶" :label-col="{ span: 5 }" :wrapper-col="{ span: 15 }">
          <a-select v-decorator="['isTop',{rules: [{ required: true, message: '请选择状态!' }],initialValue:initialFormData.isEnable!==undefined?this.initialFormData.isEnable:1}]">
            <a-select-option :value="1">是</a-select-option>
            <a-select-option :value="0">否</a-select-option>
          </a-select>
        </a-form-item>
        <a-form-item label="留言" :label-col="{span:5}" :wrapper-col="{span:15}">
          <a-textarea v-decorator="['message',{rules:[{required:true,message:'留言内容是必须的！'}],initialValue:initialFormData.name}]" autosize />
        </a-form-item>
      </a-form>
    </a-modal>
  </div>
</template>

<script>
  import urls from '../../api/urls';
  const { AdminMessageAPI }=urls;

  export default{
    data(){
      return {
        form:this.$form.createForm(this),
        AdminMessageAPI,
        initialFormData:{},
      }
    },
    props:["editorialPanelVisible","formItem"],
    mounted(){
      const {formItem={}}=this;
      if (formItem.id) this.formatInitialFormData(formItem);
    },
    methods:{
      formatInitialFormData (formItem) {
        const { id, from, fromMail,message: preMessage } = formItem;
        const to = { key: from?from.id:fromMail, label: from?from.nickName:fromMail };
        this.initialFormData = { id, to, preMessage };
      },
      toggleEdit(obj){
        if (obj === 'cancel') {
          this.form.resetFields();
          this.$emit("toggleEditorialPanel");
          this.$emit("cleanFormItem");
          this.$emit("request");
          return;
        }
        this.form.validateFields((err, values) => {
          if (err) return;
          const {formItem: { id, parentId: pid }}=this;
          const { to={} } = values;
          const netUrl = AdminMessageAPI.INSERT.url;
          const parentId = pid === 0 ? id : pid;
          const toId = typeof to.key === "number" ? to.key : undefined;
          const toMail = to.key!==undefined&&typeof to.key !== "number" && to.key !== "博主" ? to.key : "无";
          this.$emit("request",{ ...values, netUrl, parentId, toId,toMail,fromMail:"无"  });
          this.$emit("toggleEditorialPanel");
          this.$emit("cleanFormItem");
          this.form.resetFields();
        });
      }
    }
  }
</script>
<style lang="scss" scoped>
  #message-edit{

  }
</style>
