// blog_react_new/src/pages/TagManagement/EditorialForm.js
import React from 'react';
import { Form } from 'antd';
import { UrlEnum } from '@/assets/Enum';
import EditorialFormConfig from '@/pages/EditorialFormConfig';

const { getModalForm } = EditorialFormConfig;
const {
  AdminTagAPI: { INSERT, UPDATE },
  AdminSortAPI,
} = UrlEnum;

@Form.create()
class EditorialForm extends React.PureComponent {
  state = {
    initialFormData: {},
    categoryOptions: [],
  };

  componentDidMount = () => {
    const { formItem = {}, request } = this.props;
    request({ netUrl: AdminSortAPI.LIST.url, index: 1, size: 999 }, res =>
      this.setState({ categoryOptions: res.list })
    );
    if (formItem.id) this.formatInitialFormData(formItem);
  };

  formatInitialFormData = (formItem, extraObj) => {
    const { sort } = formItem;
    const initialFormData = { ...formItem, sort: { label: sort.name, key: sort.id } };
    this.setState({ initialFormData, ...extraObj });
  };

  handleSetState = (obj, func) => this.setState({ ...obj }, () => func);

  handleGetState = val => this.state[val];

  toggleEdit = obj => {
    const {
      form,
      request,
      cleanFormItem,
      toggleEditorialPanel,
      formItem: { id },
    } = this.props;
    if (obj === 'cancel') {
      form.resetFields();
      toggleEditorialPanel();
      cleanFormItem();
      request();
      return;
    }
    form.validateFields((err, values) => {
      if (err) return;
      const { sort } = values;
      const netUrl = id ? UPDATE.url : INSERT.url;
      request({ ...values, id, netUrl, sortId: sort.key });
      toggleEditorialPanel();
      cleanFormItem();
      form.resetFields();
    });
  };

  render() {
    const { form, editorialPanelVisible } = this.props;
    const { initialFormData, categoryOptions } = this.state;
    const modalFormConfig = [
      {
        fieldId: 'name',
        label: '名称',
        rules: [{ required: true, message: '名称是必须的' }],
        fieldProps: { style: { width: '86%' } },
        fieldType: 'input',
        formItemLayout: { labelCol: { span: 6 } },
      },
      {
        fieldId: 'sort',
        label: '分类',
        rules: [{ required: true, message: '分类是必须的' }],
        fieldType: 'select',
        fieldProps: {
          options: categoryOptions.map(i => ({ label: i.name, value: i.id, disabled: !i.isEnable })),
          labelInValue: true,
          style: { width: '86%' },
        },
        formItemLayout: { labelCol: { span: 6 } },
      },
      {
        fieldId: 'isEnable',
        label: '状态',
        fieldType: 'select',
        fieldProps: {
          options: [{ value: 0, label: '不可用' }, { value: 1, label: '可用' }],
          style: { width: '86%' },
        },
        initialValue: 1,
        formItemLayout: { labelCol: { span: 6 } },
      },
    ];
    return getModalForm({
      initialFormData,
      editorialPanelVisible,
      toggleEdit: this.toggleEdit,
      form,
      modalFormConfig,
      INSERT,
      UPDATE,
      width: 600,
    });
  }
}

export default EditorialForm;

// blog_new/blog_vue/src/pages/Tag/EditorialForm.vue
<template>
  <div id="tag-edit">
    <a-modal
      title="哈哈"
      :visible="editorialPanelVisible"
      width="100%"
      okText="确定"
      cancelText="取消"
      @ok="toggleEdit"
      @cancel="toggleEdit('cancel')"
    >
      <a-form :form="form" layout="horizontal">
        <a-form-item label="名称" :label-col="{span:5}" :wrapper-col="{span:15}">
          <a-input v-decorator="['name',{rules:[{required:true,message:'名称是必须的！'}],initialValue:this.initialFormData.name}]" />
        </a-form-item>
        <a-form-item label="分类" :label-col="{span:5}" :wrapper-col="{span:15}">
          <a-select :labelInValue="true" v-decorator="['sort',{rules:[{required:true,message:'分类是必须的！'}],initialValue:this.initialFormData.sort}]">
            <a-select-option v-for="item in categoryOptions.map(i => ({ label: i.name, value: i.id, disabled: !i.isEnable }))" :key="item.value" :value="item.value" :disabled="item.disabled">{{item.label}}</a-select-option>
          </a-select>
        </a-form-item>
        <a-form-item label="状态" :label-col="{ span: 5 }" :wrapper-col="{ span: 15 }">
          <a-select v-decorator="['isEnable',{rules: [{ required: true, message: '请选择状态!' }],initialValue:this.initialFormData.isEnable!==undefined?this.initialFormData.isEnable:1}]">
            <a-select-option :value="1">可用</a-select-option>
            <a-select-option :value="0">禁用</a-select-option>
          </a-select>
        </a-form-item>
      </a-form>
    </a-modal>
  </div>
</template>

<script>
  import urls from '../../api/urls';
  const { AdminTagAPI,AdminSortAPI }=urls;
  export default{
    data(){
      return {
        form:this.$form.createForm(this),
        AdminTagAPI,
        categoryOptions: [],
        initialFormData:{}
      }
    },
    props:["editorialPanelVisible","formItem"],
    mounted(){
      const formItem=this.formItem;
      if (formItem.id) this.formatInitialFormData(formItem);
      this.$emit("request",{netUrl: AdminSortAPI.LIST.url, index: 1, size: 999},res=>{this.categoryOptions= res.list;})
    },
    methods:{
      formatInitialFormData (formItem) {
        const { sort } = formItem;
        this.initialFormData = { ...formItem, sort: { label: sort.name, key: sort.id } };
      },
      toggleEdit(obj){
        if (obj === 'cancel') {
          this.form.resetFields();
          this.$emit("toggleEditorialPanel");
          this.$emit("cleanFormItem");
          this.$emit("request");
          return;
        }
        this.form.validateFields((err, values) => {
          if (err) return;
          const { sort } = values;
          const id=this.formItem.id;
          const netUrl = id ? AdminTagAPI.UPDATE.url : AdminTagAPI.INSERT.url;
          this.$emit("request",{ ...values, id, netUrl, sortId: sort.key });
          this.$emit("toggleEditorialPanel");
          this.$emit("cleanFormItem");
          this.form.resetFields();
        });
      }
    }
  }
</script>
<style lang="scss" scoped>
  #tag-edit{

  }
</style>
