// blog_react/src/pages/CategoryManagement/SortEditorialForm.js
import React from 'react';
import { Form } from 'antd';
import { UrlEnum } from '@/assets/Enum';
import EditorialFormConfig from '@/pages/EditorialFormConfig';

const { getModalForm } = EditorialFormConfig;
const {
  AdminSortAPI: { INSERT, UPDATE },
} = UrlEnum;

@Form.create()
class EditorialForm extends React.PureComponent {
  state = {
    initialFormData: {},
  };

  componentDidMount = () => {
    const { formItem = {} } = this.props;
    if (formItem.id) this.formatInitialFormData(formItem);
  };

  formatInitialFormData = (formItem, extraObj) => {
    this.setState({ initialFormData: formItem, ...extraObj });
  };

  handleSetState = (obj, func) => this.setState({ ...obj }, () => func);

  handleGetState = val => this.state[val];

  toggleEdit = obj => {
    const {
      form,
      request,
      cleanFormItem,
      toggleEditorialPanel,
      formItem: { id },
    } = this.props;
    if (obj === 'cancel') {
      form.resetFields();
      toggleEditorialPanel();
      cleanFormItem();
      request();
      return;
    }
    form.validateFields((err, values) => {
      console.log(values);
      if (err) return;
      const netUrl = id ? UPDATE.url : INSERT.url;
      request({ ...values, id, netUrl });
      toggleEditorialPanel();
      cleanFormItem();
      form.resetFields();
    });
  };

  render() {
    const { form, editorialPanelVisible } = this.props;
    const { initialFormData } = this.state;
    const modalFormConfig = [
      {
        fieldId: 'name',
        label: '名称',
        rules: [{ required: true, message: '名称是必须的' }],
        fieldProps: { style: { width: '86%' } },
        fieldType: 'input',
        formItemLayout: { labelCol: { span: 6 } },
      },
      {
        fieldId: 'disabled',
        label: '状态',
        fieldType: 'select',
        fieldProps: {
          options: [{ value: 1, label: '不可用' }, { value: 0, label: '可用' }],
          style: { width: '86%' },
        },
        initialValue: 0,
        formItemLayout: { labelCol: { span: 6 } },
      },
    ];
    return getModalForm({
      initialFormData,
      editorialPanelVisible,
      toggleEdit: this.toggleEdit,
      form,
      modalFormConfig,
      INSERT,
      UPDATE,
      width: 600,
    });
  }
}

export default EditorialForm;

// blog_new/blog_vue/src/pages/Category/SortEditorialForm.vue
<template>
  <div id="tag-edit">
    <a-modal
      :title="initialFormData.id?AdminSortAPI.UPDATE.desc['zh_CN']:AdminSortAPI.INSERT.desc['zh_CN']"
      :visible="editorialPanelVisible"
      width="100%"
      okText="确定"
      cancelText="取消"
      @ok="toggleEdit"
      @cancel="toggleEdit('cancel')"
    >
      <a-form :form="form" layout="horizontal">
        <a-form-item label="名称" :label-col="{span:5}" :wrapper-col="{span:15}">
          <a-input v-decorator="['name',{rules:[{required:true,message:'名称是必须的！'}],initialValue:this.initialFormData.name}]" />
        </a-form-item>
        <a-form-item label="状态" :label-col="{ span: 5 }" :wrapper-col="{ span: 15 }">
          <a-select v-decorator="['isEnable',{rules: [{ required: true, message: '请选择状态!' }],initialValue:this.initialFormData.isEnable!==undefined?this.initialFormData.isEnable:1}]">
            <a-select-option :value="1">可用</a-select-option>
            <a-select-option :value="0">禁用</a-select-option>
          </a-select>
        </a-form-item>
      </a-form>
    </a-modal>
  </div>
</template>

<script>
  import urls from '../../api/urls';
  const { AdminSortAPI }=urls;
  export default{
    data(){
      return {
        form:this.$form.createForm(this),
        AdminSortAPI,
        initialFormData:{}
      }
    },
    props:["editorialPanelVisible","formItem"],
    mounted(){
      const formItem=this.formItem;
      if (formItem.id) this.formatInitialFormData(formItem);
    },
    methods:{
      formatInitialFormData (formItem) {
        this.initialFormData = { ...formItem };
      },
      toggleEdit(obj){
        if (obj === 'cancel') {
          this.form.resetFields();
          this.$emit("toggleEditorialPanel");
          this.$emit("cleanFormItem");
          this.$emit("request");
          return;
        }
        this.form.validateFields((err, values) => {
          if (err) return;
          const id=this.formItem.id;
          const netUrl = id ? AdminSortAPI.UPDATE.url : AdminSortAPI.INSERT.url;
          this.$emit("request",{ ...values, id, netUrl });
          this.$emit("toggleEditorialPanel");
          this.$emit("cleanFormItem");
          this.form.resetFields();
        });
      }
    }
  }
</script>
<style lang="scss" scoped>
  #tag-edit{

  }
</style>
