// blog_react/src/pages/HomePage/HomePage.js
import React, { Fragment } from 'react';
import { connect } from 'dva';
import { Modal, Card, Col, Row, Button, Tooltip, Input, Tag, Icon, List, Tree, Avatar, Divider, Timeline } from 'antd';
import GridContent from '@/components/PageHeaderWrapper/GridContent';
import Ellipsis from '@/components/Ellipsis';
import { adminType, imgPrefix } from '@/defaultSettings';
import { timeFormat, getRandomColor } from '@/utils/utils';
import { UrlEnum } from '@/assets/Enum';

const {
  UserArticleAPI: { LIST },
  UserCateAPI,
  UserLabelAPI
} = UrlEnum;


@connect(({ articleManagement, loading }) => ({
  articleManagement,
  loading: loading.models.articleManagement,
}))
class HomePage extends React.Component {
  state = {
    conditionQuery: { title: '', category: {}, orderBy: {} },
    showSorterFlag: false,
    filterModalVisible: false,
    categoryOptions: [],
    labelOptions: [],
    temporaryCondition: {},
    timelines: []
  };

  componentDidMount = () => {
    this.request({ index: 1, size: 6 });
    this.request({ size: 5, conditionQuery: { orderBy: { name: "create_time", by: "desc" } } }, (res) => this.setState({ timelines: res.list }));
    this.request({ netUrl: UserLabelAPI.LIST.url, index: 1, size: 100 }, (res) =>
      this.setState({ labelOptions: res.list })
    );
    this.request({ netUrl: UserCateAPI.LIST.url, index: 1, size: 100, prettyFormat: true }, (res) =>
      this.setState({ categoryOptions: res.list })
    );
  }

  componentWillUnmount = () => this.props.dispatch({ type: 'articleManagement/save', payload: { list: [] } });

  request = (params, callback) => {
    const { conditionQuery: con } = this.state;
    const conditionQuery = { ...con };
    delete conditionQuery.filteredSortArr;
    const payload = { netUrl: LIST.url, conditionQuery, ...params };
    this.props.dispatch({ type: 'articleManagement/handleArticles', payload, callback });
  };

  handleShowALL = () =>
    this.setState({ conditionQuery: {}, temporaryCondition: {} }, () => {
      this.request({ index: 1 });
      this.inputSearch.input.state.value = '';
    });

  handlePageChange = (index, size) => this.request({ index, size });

  handleOnSearch = val =>
    this.setState(
      oldState => ({
        conditionQuery: { ...oldState.conditionQuery, title: val.replace(/(^\s*)|(\s*$)/g, '') },
      }),
      () => this.request({ index: 1 })
    );

  toggleShowSorter = () => {
    const {
      articleManagement: { list = [] },
    } = this.props;
    if (!list.length) return;
    this.setState(oldState => ({ showSorterFlag: !oldState.showSorterFlag }));
  };

  sort = e => {
    if (e === 'default') {
      this.setState(
        oldState => ({ conditionQuery: { ...oldState.conditionQuery, orderBy: {} } }),
        () => this.request({ index: 1 })
      );
      this.showSorterFlag();
      return;
    }
    const { id: name } = e.currentTarget;
    const {
      conditionQuery: { orderBy = {} },
    } = this.state;
    this.setState(
      oldState => ({
        conditionQuery: {
          ...oldState.conditionQuery,
          orderBy: { name, by: orderBy.by === 'asc' ? 'desc' : 'asc' },
        },
      }),
      () => this.request({ index: 1 })
    );
  };

  toggleFilterModal = () =>
    this.setState(oldState => ({ filterModalVisible: !oldState.filterModalVisible }));

  filterRequest = method => {
    if (method === 'clear') {
      this.setState({ temporaryCondition: {} });
      return;
    }
    if (method !== "noModal") this.toggleFilterModal();
    let filterflag = false;
    if (method === 'exit') {
      const {
        conditionQuery: { filteredSortArr = [], labelIds = [] },
      } = this.state;
      filterflag = filteredSortArr.length > 0 || labelIds.length;
      this.setState(oldState => ({
        temporaryCondition: { ...oldState.temporaryCondition, filteredSortArr, labelIds, filterflag },
      }));
      return;
    }
    const {
      temporaryCondition: { filteredSortArr = [], labelIds = [] },
    } = this.state;
    filterflag = filteredSortArr.length > 0 || labelIds.length > 0;
    const category = { sort: [], child: [] };
    filteredSortArr.forEach(item => {
      const arr = item.split('-');
      if (arr.length === 1) {
        category.sort.push(parseInt(arr.pop(), 10));
      } else if (!category.sort.includes(parseInt(arr[0], 10))) {
        category.child.push(parseInt(arr.pop(), 10));
      }
    });
    this.setState(
      oldState => ({
        conditionQuery: { ...oldState.conditionQuery, category, filteredSortArr, labelIds },
        temporaryCondition: { ...oldState.temporaryCondition, filterflag },
      }),
      () => this.request({ index: 1 })
    );
  };

  conditionTreeSelect = filteredSortArr =>
    this.setState(oldState => ({
      temporaryCondition: { ...oldState.temporaryCondition, filteredSortArr },
    }));

  render() {
    const {
      articleManagement: { total = 6, list = [], size = 6, index = 1 },
      loading,
    } = this.props;
    const {
      showSorterFlag,
      filterModalVisible,
      categoryOptions,
      labelOptions,
      conditionQuery,
      temporaryCondition,
      timelines
    } = this.state;
    return (
      <GridContent>
        <Card>
          <Row type="flex" align="middle" style={{ marginBottom: '15px' }}>
            <Col xs={12} sm={13} md={15} lg={16} xl={17}>
              <Button
                icon="filter"
                type={temporaryCondition.filterflag ? 'danger' : 'primary'}
                size="small"
                onClick={this.toggleFilterModal}
              >
                筛选&nbsp;
              </Button>
              <Button
                icon={showSorterFlag ? 'right-circle-o' : 'left-circle-o'}
                type="primary"
                size="small"
                onClick={this.toggleShowSorter}
                style={{ marginLeft: '20px' }}
              >
                排序&nbsp;
              </Button>
              {showSorterFlag && (
                <Fragment>
                  <Tag
                    color="magenta"
                    style={{ marginLeft: '10px' }}
                    onClick={() => this.sort('default')}
                  >
                    默认
                  </Tag>
                  <Tag color="magenta" id="title" style={{ marginLeft: '5px' }} onClick={this.sort}>
                    标题
                    <Icon
                      type={
                        conditionQuery.orderBy &&
                          conditionQuery.orderBy.name === 'title' &&
                          conditionQuery.orderBy.by === 'desc'
                          ? 'down'
                          : 'up'
                      }
                    />
                  </Tag>
                  <Tag
                    color="magenta"
                    id="create_time"
                    style={{ marginLeft: '5px' }}
                    onClick={this.sort}
                  >
                    创建时间
                    <Icon
                      type={
                        conditionQuery.orderBy &&
                          conditionQuery.orderBy.name === 'create_time' &&
                          conditionQuery.orderBy.by === 'desc'
                          ? 'down'
                          : 'up'
                      }
                    />
                  </Tag>
                  <Tag
                    color="magenta"
                    id="modified_time"
                    style={{ marginLeft: '5px' }}
                    onClick={this.sort}
                  >
                    修改时间
                    <Icon
                      type={
                        conditionQuery.orderBy &&
                          conditionQuery.orderBy.name === 'modified_time' &&
                          conditionQuery.orderBy.by === 'desc'
                          ? 'down'
                          : 'up'
                      }
                    />
                  </Tag>
                </Fragment>
              )}
            </Col>
            <Col xs={2} sm={2} md={1} lg={1} xl={1}>
              <Tooltip title="默认展示">
                <Button
                  type="primary"
                  icon="home"
                  shape="circle"
                  size="small"
                  onClick={this.handleShowALL}
                />
              </Tooltip>
            </Col>
            <Col xs={10} sm={9} md={8} lg={7} xl={6}>
              <Input.Search
                placeholder="请输入标题"
                onSearch={this.handleOnSearch}
                enterButton
                allowClear
                ref={inputSearch => {
                  this.inputSearch = inputSearch;
                }}
              />
            </Col>
          </Row>
          <Row gutter={16}>
            <Col span={17}>
              <List
                loading={loading}
                itemLayout="vertical"
                dataSource={list}
                pagination={{
                  showQuickJumper: true,
                  showSizeChanger: true,
                  onChange: this.handlePageChange,
                  onShowSizeChange: this.handlePageChange,
                  pageSizeOptions: ['6', '12', '18', '24'],
                  pageSize: size,
                  defaultPageSize: 6,
                  total,
                  current: index,
                }}
                renderItem={item => (
                  <List.Item
                    key={item.id}
                    actions={[
                      <span>
                        <Icon type="edit" />
                        &nbsp;
                        {timeFormat(Number(new Date(item.modified_time)))}
                      </span>,
                      <Icon type="star-o" />,
                      <Icon type="like-o" />,
                      <Icon type="message" />,
                      <div>
                        {item.label.map(i => (
                          <Tag color="volcano">{i.name}</Tag>
                        ))}
                      </div>,
                    ]}
                    extra={
                      <img
                        width={200}
                        height={110}
                        alt="logo"
                        src={
                          item.image_url
                            ? `${imgPrefix}${item.image_url}`
                            : 'https://gw.alipayobjects.com/zos/rmsportal/mqaQswcyDLcXyDKnZfES.png'
                        }
                      />
                    }
                    style={{ position: 'relative', overflow: 'hidden' }}
                  >
                    {item.is_top === 1 && (
                      <div
                        style={{
                          position: 'absolute',
                          background: 'gray',
                          top: '5px',
                          right: '-55px',
                          width: '150px',
                          textAlign: 'center',
                          overflow: 'hidden',
                          transform: 'rotate(40deg)',
                        }}
                      >
                        <span style={{ color: 'yellow' }}>置顶</span>
                      </div>
                    )}
                    <List.Item.Meta
                      avatar={
                        <Avatar src="https://zos.alipayobjects.com/rmsportal/ODTLcjxAfvqbxHnVXCYX.png" />
                      }
                      title={
                        <a
                          href={`${window.location.origin}/${adminType}/article/${item.id}`}
                          target="_blank"
                          rel="noreferrer noopener"
                        >
                          {item.title}
                          &nbsp;&nbsp;
                          <Tag color="purple">
                            <Icon type="tag" />
                            {item.sort_name},{item.category_name}
                          </Tag>
                        </a>
                      }
                      style={{ marginBottom: "0px" }}
                    />
                    <Ellipsis lines={2} style={{ height: '40px' }}>
                      <span style={{ paddingLeft: '30px', fontWeight: 'bold' }}>摘要：</span>
                      {item.abstract ? item.abstract : '无'}
                    </Ellipsis>
                  </List.Item>
                )}
              />
            </Col>
            <Col span={7}>
              <div style={{ textAlign: "center" }}>
                <p><Avatar size={200} src="https://zos.alipayobjects.com/rmsportal/ODTLcjxAfvqbxHnVXCYX.png" /></p>
                <span style={{ fontSize: "25px", fontWeight: "bold", margin: "10px" }}>博客</span>
                <Divider style={{ margin: "5px 0px" }}>
                  <span>
                    <a><Icon type="github" /></a>&nbsp;&nbsp;
                    <a><Icon type="cloud" /></a>
                  </span>
                </Divider>
                <span>这个人很懒，什么都没留下</span>
              </div>
              <div>
                <Divider style={{ margin: "25px 0px 10px 0px" }}><Icon type="tags" style={{ color: "purple" }} /></Divider>
                {
                  labelOptions.map(i => (
                    <Tag
                      onClick={() => {
                        this.setState(oldState => ({
                          temporaryCondition: { ...oldState.temporaryCondition, labelIds: [i.id] },
                        }), () => this.filterRequest("noModal"))
                      }}
                      color={getRandomColor()}
                      style={{ fontSize: "13px",margin:"3px" }}
                    >
                      {i.name}
                    </Tag>
                  ))
                }
              </div>
              <div>
                <Divider style={{ margin: "25px 0px 10px 0px" }}><Icon type="clock-circle" style={{ color: "blue" }} /></Divider>
                <Timeline mode="alternate">
                  {timelines.map(i => (
                    <Timeline.Item color={getRandomColor()}>
                      <b>{timeFormat(Number(new Date(i.modified_time)))}</b>
                      <a
                        href={`${window.location.origin}/${adminType}/article/${i.id}`}
                        target="_blank"
                        rel="noreferrer noopener"
                        style={{ display: "block" }}
                      >
                        {i.title}
                      </a>
                    </Timeline.Item>
                  )
                  )}
                  <Timeline.Item><a>more...</a></Timeline.Item>
                </Timeline>
              </div>
            </Col>
          </Row>
          <Modal
            destroyOnClose
            visible={filterModalVisible}
            title="请选择筛选条件"
            onCancel={() => this.filterRequest('exit')}
            footer={[
              <Button onClick={() => this.filterRequest('exit')}>不更改并退出</Button>,
              <Button type="danger" onClick={() => this.filterRequest('clear')}>
                清空
              </Button>,
              <Button type="primary" onClick={this.filterRequest}>
                确定
              </Button>,
            ]}
          >
            <Tree
              checkable
              showLine
              onCheck={this.conditionTreeSelect}
              defaultExpandedKeys={temporaryCondition.filteredSortArr || []}
              checkedKeys={temporaryCondition.filteredSortArr || []}
            >
              {categoryOptions.map(item => (
                <Tree.TreeNode
                  title={item.name}
                  key={`${item.id}`}
                  selectable={false}
                  disabled={item.disabled}
                >
                  {item.children.map(i => (
                    <Tree.TreeNode
                      title={i.name}
                      key={`${item.id}-${i.id}`}
                      selectable={false}
                      disabled={item.disabled === 0 ? i.disabled : true}
                    />
                  ))}
                </Tree.TreeNode>
              ))}
            </Tree>
            {
                labelOptions.map(item=>(
                  <Tag.CheckableTag 
                    key={item.id} 
                    checked={temporaryCondition.labelIds&&temporaryCondition.labelIds.includes(item.id)}
                    onChange={(val,options)=>console.log(val,options)}
                  >
                    {item.name}
                  </Tag.CheckableTag>
                ))
              }
          </Modal>
        </Card>
      </GridContent>
    );
  }
}
export default HomePage;

// blog_new/blog_vue/src/pages/Homepage.vue
<template>
  <div id="homepage">
    <a-spin :spinning="spinningFlag">
      <a-drawer
        title="搜索框"
        placement="top"
        :height="100"
        @close="toggleShowSearch"
        :visible="$store.state.search.searchBoxFlag"
        :zIndex="998"
      >
        <div style="display:flex;justify-content:space-between">
          <a-input-search
            placeholder="文章搜索"
            v-model="conditionQuery.title"
            @search="searchArticle"
            enterButton
            ref="searchInput"
          />
          <a-button type="danger" shape="circle" icon="reload" @click="resetTitle" />
        </div>
      </a-drawer>
      <a-card
        v-for="item in list"
        :key="item.id"
        class="card"
        @click="readArticle(item.id)"
      >
        <img
          alt="pic"
          :src="`${baseImgUrl}${item.imageUrl}`||'https://gw.alipayobjects.com/zos/rmsportal/JiqGstEfoWAOHiTxclqi.png'"
          slot="cover"
        />
        <template class="ant-card-actions" slot="actions">
          <a-icon type="star-o" />
          <a-icon type="like-o" />
          <a-icon type="message" />
        </template>
        <a-card-meta
          :title="item.title"
        >
          <template slot="description">
            <div class="tag-and-date">
              <span>
                <a-icon type="tags" v-if="item.tags&&item.tags.length" />
                {{item.tags&&item.tags.map(i=>i.name).join(", ")}}
              </span>
              <span>
                <a-icon type="clock-circle" />
                {{item.createDate|dateFormat("YYYY-MM-DD")}}
              </span>
            </div>
            <div class="abstract">
              <b>摘要：</b>
              {{item.abstract}}
            </div>
          </template>
        </a-card-meta>
        <a-tag color="purple" class="category" v-show="item.category!==undefined">
          <a-icon type="tag" />&nbsp;{{item.category.sort.name}},{{item.category.name}}
        </a-tag>
        <div class="top" v-if="item.isTop===1">置顶</div>
      </a-card>
      <div class="more" v-if="moreFlag && !spinningFlag">
        <a-button @click="loadMore">加载更多</a-button>
      </div>
    </a-spin>
  </div>
</template>

<script>
import {baseImgUrl} from '../utils/defaultSetting.js'
import UserArticle from '../api/UserArticle';
const userArticleAPI=new UserArticle();
import request from '../api/request';
import urls from '../api/urls';
const {UserArticleAPI}=urls;
import vm from '../main';
export default {
  data () {
    return {
      list:[],
      total:0,
      index:1,
      size:10,
      moreFlag:true,
      baseImgUrl,
      conditionQuery: { title: '', category: {}, orderBy: {} },
      spinningFlag:false,
    }
  },
  mounted(){
    console.log(999999,vm)
    this.getArticleList();
  },
  methods:{
    async getArticleList(paramsObj={},isConcat){
      const {index=this.index,size=this.size}=paramsObj;
      const newParamsObj={
        size,
        index,
        conditionQuery:this.conditionQuery,
        ...paramsObj
      }
      const data=await request(UserArticleAPI.LIST.url,newParamsObj);
      if(!data) return;
      const {list,total}=data;
      const newList=isConcat?[...this.list,...list]:list;
      this.list=newList;
      this.index=index;
      this.total=total;
      this.moreFlag=newList.length!==total;
    },
    // getArticleList(paramsObj={},isConcat){
    //   this.spinningFlag=true;
    //   const {index=this.index,size=this.size}=paramsObj;
    //   userArticleAPI.list({
    //     size,
    //     index,
    //     conditionQuery:this.conditionQuery,
    //     ...paramsObj
    //   })
    //   .then(res=>{
    //     const {data:{list,total}}=res;
    //     const newList=isConcat?[...this.list,...list]:list;
    //     this.list=newList;
    //     this.index=index;
    //     this.total=total;
    //     this.moreFlag=newList.length!==total;
    //     this.spinningFlag=false;
    //   })
    //   .catch(e=>this.$error({title:"请求出错！"}));
    // },
    loadMore(){
      this.getArticleList({index:this.index+1},true);
    },
    toggleShowSearch(){
      this.$store.dispatch({type:"search/toggleSearchBox"});
    },
    searchInputFocus(){
      this.$nextTick(()=>this.$refs.searchInput.focus());
    },
    searchArticle(){
      this.getArticleList({index:1});
      this.toggleShowSearch();
    },
    resetTitle(){
      this.conditionQuery.title="";
      this.getArticleList({index:1});
      this.toggleShowSearch();
    },
    readArticle(id){
      this.$router.push(`/read/${id}`);
    },
  }
}
</script>

<style lang="scss" scoped>
  #homepage{
    width:100%;
    .card{
      margin-bottom:10px;
      position: relative;
      overflow: hidden;
      &:last-of-type{
        margin-bottom: 0;
      }
      .abstract{
        text-indent: 2em;
      }
      .tag-and-date{
        display: flex;
        justify-content: space-between;
        font-size:10px;
      }
      .category{
        position:absolute;
        top:0px;
        left:0px;
      }
      .top{
        position: absolute;
        background: gray;
        top: 5px;
        right: -55px;
        width: 150px;
        text-align: center;
        transform: rotate(40deg);
        color:yellow;
      }
    }
    /deep/ .ant-card-meta-title{
      white-space: normal;
    }
    .more{
      margin-top:10px;
      text-align: center;
    }
  }
</style>
