// blog_new/foreground_react/src/pages/ReplyManagement/EditorialForm.js
import React from 'react';
import { Form } from 'antd';
import { UrlEnum } from '@/assets/Enum';
import EditorialFormConfig from '@/pages/EditorialFormConfig';

const { getModalForm } = EditorialFormConfig;
const {
  AdminReplyAPI: { INSERT },
  AdminArticleAPI,
} = UrlEnum;
const initArticleContainer = {
  netUrl: AdminArticleAPI.LIST.url,
  list: [],
  total: 0,
  index: 1,
  size: 6,
  query: '',
};

@Form.create()
class EditorialForm extends React.PureComponent {
  state = {
    articlecontainer: initArticleContainer,
    initialFormData: {},
  };

  componentDidMount = () => {
    const { formItem = {} } = this.props;
    if (formItem.id) this.formatInitialFormData(formItem);
  };

  formatInitialFormData = (formItem, extraObj) => {
    const { id, from, reply: preReply, article: art } = formItem;
    const article = { key: art.id, label: art.title };
    const to = { key: from.id, label: from.nickName };
    const initialFormData = { id, to, preReply, article };
    this.setState({ initialFormData, ...extraObj });
  };

  toggleEdit = obj => {
    const {
      form,
      request,
      cleanFormItem,
      toggleEditorialPanel,
      formItem: { id, parentId: pid },
    } = this.props;
    if (obj === 'cancel') {
      form.resetFields();
      toggleEditorialPanel();
      cleanFormItem();
      request();
      return;
    }
    form.validateFields((err, values) => {
      if (err) return;
      const { article, to } = values;
      const netUrl = INSERT.url;
      const parentId = pid === 0 ? id : pid;
      const toId = to && to.key;
      request({ ...values, netUrl, parentId, toId, articleId: article.key });
      toggleEditorialPanel();
      cleanFormItem();
      form.resetFields();
    });
  };

  searchItem = ({ query, container, pageIndex, pageSize }) => {
    const { request } = this.props;
    const { index: preIndex, size: preSize, netUrl } = container;
    const index = pageIndex || preIndex;
    const size = pageSize || preSize;
    request({ netUrl, index, size, conditionQuery: { title: query } }, res =>
      this.setState(oldState => ({
        articlecontainer: { ...oldState.articlecontainer, ...res, index, size, query },
      }))
    );
  };

  getSelectorConfig = ({ container, ...otherProps }) => {
    const { list, total, index: current, size: pageSize } = container;
    return {
      pagination: {
        total,
        current,
        pageSize,
        defaultPageSize: 6,
        usePagination: total > 6,
        onChange: (i, s) =>
          this.searchItem({ query: container.query, container, pageIndex: i, pageSize: s }),
      },
      options: list.map(i => ({ label: i.title, value: i.id })),
      labelInValue: true,
      filterOption: false,
      showSearch:true,
      onSearch: (query) => this.searchItem({ query, container }),
      onMouseEnter: () => this.searchItem({ query: '', container }),
      style: { width: '86%' },
      ...otherProps,
    };
  };

  render() {
    const { form, editorialPanelVisible } = this.props;
    const { articlecontainer, initialFormData } = this.state;
    const modalFormConfig = [
      {
        fieldId: 'article',
        label: '文章',
        rules: [{ required: true, message: '文章是必须的' }],
        fieldType: 'select',
        fieldProps: {
          ...this.getSelectorConfig({ container: articlecontainer, disabled: initialFormData.id !== undefined }),
          style: { width: '86%' },
        },
        formItemLayout: { labelCol: { span: 6 } },
      },
      initialFormData.id !== undefined && {
        fieldId: 'to',
        label: '评论人',
        rules: [{ required: true, message: '评论人是必须的' }],
        fieldType: 'select',
        fieldProps: {
          options: [],
          labelInValue: true,
          disabled: true,
          style: { width: '86%' },
        },
        formItemLayout: { labelCol: { span: 6 } },
      },
      initialFormData.id !== undefined && {
        fieldId: 'preReply',
        label: '内容',
        fieldType: "node",
        fieldNode: <span>{initialFormData.preReply}</span>,
        fieldProps: {
          style: { width: '86%' },
        },
        formItemLayout: { labelCol: { span: 6 } },
      },
      {
        fieldId: 'isTop',
        label: '是否置顶',
        rules: [{ required: true, message: '该项是必须的' }],
        fieldType: 'select',
        fieldProps: {
          options: [{ value: 1, label: '是' }, { value: 0, label: '否' }],
          style: { width: '86%' },
        },
        initialValue: 1,
        formItemLayout: { labelCol: { span: 6 } },
      },
      {
        fieldId: 'reply',
        label: '回复',
        rules: [{ required: true, message: '评论内容是必须的' }],
        fieldProps: { style: { width: '86%' }, autosize: true, rows: 2 },
        fieldType: 'textArea',
        formItemLayout: { labelCol: { span: 6 } },
      },
    ];
    return getModalForm({
      initialFormData,
      editorialPanelVisible,
      toggleEdit: this.toggleEdit,
      form,
      modalFormConfig,
      INSERT,
      UPDATE:INSERT,
      width: 600,
    });
  }
}

export default EditorialForm;

// blog_new/blog_vue/src/pages/Reply/EditorialForm.vue
<template>
  <div id="reply-edit">
    <a-modal
      :title="initialFormData.id?AdminReplyAPI.UPDATE.desc['zh_CN']:AdminReplyAPI.INSERT.desc['zh_CN']"
      :visible="editorialPanelVisible"
      width="100%"
      okText="确定"
      cancelText="取消"
      @ok="toggleEdit"
      @cancel="toggleEdit('cancel')"
    >
      <a-form :form="form" layout="horizontal">
        <a-form-item label="文章" :label-col="{span:5}" :wrapper-col="{span:15}">
          <a-select 
            v-decorator="['article',{rules:[{required:true,message:'文章是必须的！'}],initialValue:this.initialFormData.article}]" 
            :disabled="this.initialFormData.id !== undefined" 
            :labelInValue="true" 
            :filterOption= "false"
            :showSearch="true"
            @search="(query) => this.searchItem({ query, container:this.articlecontainer })"
            @focus="() => this.searchItem({ query: '', container:this.articlecontainer })"
          >
            <a-select-option v-for="item in this.articlecontainer.list.map(i => ({ label: i.title, value: i.id }))" :key="item.value" :value="item.value">{{item.label}}</a-select-option>
            <a-select-option :disabled="true" :key="-1">
              <a-pagination 
                style="text-align:center;"
                size="small"
                :current="this.articlecontainer.index"
                :total="this.articlecontainer.total"
                :pageSize="this.articlecontainer.size"
                @change="(i, s) =>this.searchItem({ query: this.articlecontainer.query, container:this.articlecontainer, pageIndex: i, pageSize: s })"
              />
            </a-select-option>
          </a-select>
        </a-form-item>
        <a-form-item label="评论人" :label-col="{span:5}" :wrapper-col="{span:15}" v-if="this.initialFormData.id !== undefined">
          <a-select 
            v-decorator="['to',{rules:[{required:true,message:'评论人是必须的！'}],initialValue:this.initialFormData.to}]" 
            :disabled="true" 
            :labelInValue="true" 

          >
            <!-- <a-select-option></a-select-option> -->
          </a-select>
        </a-form-item>
        <a-form-item label="内容" :label-col="{span:5}" :wrapper-col="{span:15}" v-if="this.initialFormData.id !== undefined">
          <span>{{this.initialFormData.preReply}}</span>
        </a-form-item>
        <a-form-item label="置顶" :label-col="{ span: 5 }" :wrapper-col="{ span: 15 }">
          <a-select v-decorator="['isTop',{rules: [{ required: true, message: '请选择状态!' }],initialValue:this.initialFormData.isEnable!==undefined?this.initialFormData.isEnable:1}]">
            <a-select-option :value="1">是</a-select-option>
            <a-select-option :value="0">否</a-select-option>
          </a-select>
        </a-form-item>
        <a-form-item label="回复" :label-col="{span:5}" :wrapper-col="{span:15}">
          <a-textarea v-decorator="['reply',{rules:[{required:true,message:'回复内容是必须的！'}],initialValue:this.initialFormData.name}]" autosize />
        </a-form-item>
      </a-form>
    </a-modal>
  </div>
</template>

<script>
  import urls from '../../api/urls';
  const { AdminReplyAPI,AdminArticleAPI }=urls;
  const initArticleContainer = {
    netUrl: AdminArticleAPI.LIST.url,
    list: [],
    total: 0,
    index: 1,
    size: 6,
    query: '',
  };
  export default{
    data(){
      return {
        form:this.$form.createForm(this),
        AdminReplyAPI,
        initialFormData:{},
        articlecontainer: initArticleContainer,
      }
    },
    props:["editorialPanelVisible","formItem"],
    mounted(){
      const {formItem={}}=this;
      if (formItem.id) this.formatInitialFormData(formItem);
    },
    methods:{
      formatInitialFormData (formItem) {
        const { id, from, reply: preReply, article: art } = formItem;
        const article = { key: art.id, label: art.title };
        const to = { key: from.id, label: from.nickName };
        this.initialFormData = { id, to, preReply, article };
      },
      searchItem ({ query, container, pageIndex, pageSize }) {
        const { index: preIndex, size: preSize, netUrl } = container;
        const index = pageIndex || preIndex;
        const size = pageSize || preSize;
        this.$emit("request",{netUrl, index, size, conditionQuery: { title: query } },res=>{
          this.articlecontainer={...this.articlecontainer,...res, index, size, query};
        });
      },
      toggleEdit(obj){
        if (obj === 'cancel') {
          this.form.resetFields();
          this.$emit("toggleEditorialPanel");
          this.$emit("cleanFormItem");
          this.$emit("request");
          return;
        }
        this.form.validateFields((err, values) => {
          if (err) return;
          const { article, to } = values;
          const netUrl = INSERT.url;
          const parentId = pid === 0 ? id : pid;
          const toId = to && to.key;
          this.$emit("request",{ ...values, netUrl, parentId, toId, articleId: article.key  });
          this.$emit("toggleEditorialPanel");
          this.$emit("cleanFormItem");
          this.form.resetFields();
        });
      }
    }
  }
</script>
<style lang="scss" scoped>
  #reply-edit{

  }
</style>
